//....OBJECT METHODS ....ONLY IN ES6 (NEW)
// Object.assign()
// Object.is()
// Object.setPrototypeOf()
// Object.getOwnPropertySymbols()
// Object.getOwnPropertyDescriptors()

//....ES5,ES6....(COMMON)

// ....Static Object Methods....
// Object.assign()
// Object.create()
// Object.defineProperty()
// Object.defineroperties()
// Object.entries()
// Object.freeze()
// Object.fromEntries()
// Object.getOwnPropertyDescriptor()
// Object.getOwnPropertyDescriptors()
// Object.getOwnPropertyNames()
// Object.getOwnPropertySymbols()
// Object.getPrototypeOf()
// Object.is()
// Object.isExtensible()
// Object.isFrozen()
// Object.isSealed()
// Object.keys()
// Object.preventExtensions()
// Object.seal()
// Object.setPrototypeOf()
// Object.values()

// ....Object Prototype Methods....
// hasOwnProperty()
// isPrototypeOf()
// propertyIsEnumerable()
// toLocaleString()
// toString()
// valueOf()
